### PR TITLE
trait is missing, commenting trait for temporary update

### PR DESCRIPTION
**Pull request by awaisali3405**

### CODE REVIEW

**Comment by awaisali3405** [comment]
The trait "hasPivotData" is not available in new version of the filament v 3.0

**Comment by CodeWithDennis** [comment]
@saade Can you confirm this or does it simply require a Filament upgrade through composer? (#91 )

**Comment by saade** [comment]
@CodeWithDennis your plugin extends `Field`, not `Select` (where the trait is), that's why we need the trait in your project too.

**Comment by awaisali3405** [comment]
no in filament 3 there no "hasPivotData" trait . So this trait is no longer existing when install this package in my new filament project.

**Comment by awaisali3405** [comment]
There is no function related to the hasPivotData trait just remove it i double checked it

**Comment by saade** [comment]
There is, it is available since v3.2.36, just run composer update and you're good to go

**Comment by awaisali3405** [comment]
https://github.com/filamentphp/filament/tree/3.x/packages/forms/src/Concerns
i have check all library there is no trait plz recheck

**Comment by saade** [comment]
@awaisali3405 man, HasPivotData was introduced by me in https://github.com/filamentphp/filament/pull/11432. I know what i'm saying.

Here's the file.
https://github.com/filamentphp/filament/blob/3.x/packages/forms/src/Components/Concerns/HasPivotData.php

**Comment by saade** [comment]
You're probably running an old version of Filament. Make sure you're on `v3.2.36` or above.

**Comment by awaisali3405** [comment]
oh sorry man my mistake for not version in composer lock
Thank for you support.

**Pull request closed without merging**
