### PR TITLE
Small Improvements

### PR DESCRIPTION
**Pull request by saade**
Hey! Thanks for your plugin!

I've started using it today, and wanted to contribute with some small improvements.

### JS params
Parameters were being passed inside a string, this was causing `boolean` values to be passed as `'1'` and `'0'`

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>
      
    </td>
    <td>
       
    </td>
  </tr>
</table>

### Flickering
Although a small flicker still occurs, its much better than before. I think the flickering can't be avoided, but now it has the same flickering as the Filament's Core Select Input

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>
      <video src="https://github.com/CodeWithDennis/filament-select-tree/assets/14329460/5af4e4b4-33a2-42e4-86db-9df2cd9dfcc8" />
    </td>
    <td>
         <video src="https://github.com/CodeWithDennis/filament-select-tree/assets/14329460/f0a1390f-50ce-4d88-a961-3900ffdeafad" />
    </td>
  </tr>
</table>

### Alpine clashing with other plugins
This is not this plugin fault, [filament-adjacency-list](https://github.com/saade/filament-adjacency-list) uses a `tree()` named alpine component too, this causes our plugins to not be compatible when used together in the same form.

I've renamed mine to `adjacencyList()` but wanted to contribute to yours too, since `tree()` is too generic, i've renemed yours to `selectTree()`.

### Asset renaming and merging
I've merged your two assets `tree` and `custom` into a `index` one. Your plugin now ships with only one css file and only one request is made to grab the asset. This helps poor connections to load the plugin faster since its only one file to request.

### Other 
- Code formatting

There is no BC in this PR, feel free to review and ask for changes. Thanks!

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
Hey, thank you for your help! I can't recall the exact reason, but I had to input it as a string. If you could confirm that everything is still functioning as intended im fine with it!. @saade

**Comment by saade** [comment]
@CodeWithDennis  Here's the checklist:

- ✅  `searchable()`
- ✅  `withCount()`
- ✅  `placeholder()`
- ✅  `enableBranchNode()`
- ✅  `disabled()`
- ✅  `independent()`
- ✅  `alwaysOpen()`
- ✅  `clearable()`
- ✅  `emptyLabel()`
- ✅  `expandSelected()`
- ✅   `grouped()`
- ✅  `defaultOpenLevel()`
- ✅  `direction()`
- ✅  `rtl()`

**Comment by saade** [comment]
Seems everything is covered 👍🏼

**Comment by mohamedsabil83** [comment]
Thanks, @CodeWithDennis, for the helpful package and @saade, for the valuable contributions.

After this PR, the **$set** method is not applied to update **select-tree** value anymore:
```php
->hintAction(fn () => Forms\Components\Actions\Action::make('add_category')
    ->label(__('Add Category'))
    ->icon('heroicon-m-plus')
    ->action(function ($component, array $data, $form, Get $get, Set $set): void {
        $record = $component->getRelationship()->getRelated();
        $record->fill($data);
        $record->save();

        $set('shop_category_id', [...Arr::wrap($get('shop_category_id')), $record->getKey()]);
    })
    ->form([
        Forms\Components\TextInput::make('name')
            ->label(__('validation.attributes.name'))
            ->required()
            ->rule(fn ($livewire) => UniqueJsonRule::for(table: 'shop_categories', column: 'name', locale: $livewire->activeLocale)),
        SelectTree::make('parent_id')
            ->label(__('validation.attributes.parent_category'))
            ->relationship(
                relationship: 'category',
                titleAttribute: 'name',
                parentAttribute: 'parent_id',
                modifyQueryUsing: fn ($query) => $query
            )
            ->enableBranchNode()
            ->defaultOpenLevel(10),
    ])
)
```

When removing **wire:ignore** & **x-ignore**, the new value was selected, but the field disappeared after.

I comment here, but I can post a new issue if you'd like.

**Comment by saade** [comment]
Thats strange, it was already there before 🤔 I'll take a look later tonight

**Pull request merged**
