### PR TITLE
fix style dark in button clear

### PR DESCRIPTION
**Pull request by gpibarra**
chrome-capture-2024-10-27

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
Hi @gpibarra, thanks for your effort! However, the color of the close button is the same as the default select field in Filament. If you'd like to change it, you can do that in your theme's CSS file.

**Comment by gpibarra** [comment]
Hi @CodeWithDennis , the button is NOT the same in terms of css, if I change the template this does not change.

On the contrary, the styles of this button (and its svg content) are replicated and match the original button. 

The code I just put is exactly the same as the code that is in the original repository https://github.com/filamentphp/forms/blob/68c9f7f4bd9677f6f99d21396dfbe69cfa142584/resources/css/components/select.css#L117

**Comment by CodeWithDennis** [comment]
Could you show a standard select field and a select tree next to each other? They seem identical to me on my side.

**Comment by gpibarra** [comment]
Sorry for my English, maybe I didn't explain myself well.
When I say THEY ARE NOT THE SAME, I mean that they are not linked, that is, if the original Filament theme is changed, it will not impact the style of the button in this library.
So, the icons are copied and ARE EQUALS, although the style for the dark theme was not copied, which is what I would be adding in this PR.

**Comment by CodeWithDennis** [comment]
Got it. So you’re saying that a normal select and a tree select in your project look the same due to their shared styles. Could you provide an example with a side by side view.

**Comment by gpibarra** [comment]
When installing the select-tree library, in light mode, the button looks the same, since the styles of `.treeselect-input__clear` in `https://github.com/CodeWithDennis/filament-select-tree/blob/3. x/resources/css/index.css` are the same as those of normal select with the class `.choices__button` in `https://github.com/filamentphp/forms/blob/3. x/resources/css/components/ select.css`.

But in dark mode, filament had a specific style for `.dark .choices__button` while here there was no style for `.dark .treeselect-input__clear`.

The video shows that the select-tree button, when switched to dark mode, is almost invisible, while normal-select, in dark mode, has a color that allows it to be seen correctly.

**Comment by CodeWithDennis** [comment]
Sorry for the misunderstanding; it looks like a good fix. Thanks!

**Pull request merged**
