### PR TITLE
add rtl for select input

### PR DESCRIPTION
**Pull request by ariaieboy**
I am waiting for this PR to be merged https://github.com/dipson88/treeselectjs/pull/84

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
I am assuming you are gonna add a RTL method?

**Comment by ariaieboy** [comment]
> I am assuming you are gonna add a RTL method?

My implementation does not need any RTL method; users only need to use an RTL locale in laravel, and since the `dir` will be set as RTL when you use an RTL language in filament, everything is going to work without any configuration.

But it depends on this https://github.com/dipson88/treeselectjs/pull/84 PR. 
If the project's maintainer decides that using HTML `dir` is not a good option and we need to introduce a new option to the library, we might need to change more things or add a method.

**Comment by CodeWithDennis** [comment]
Nice job, sounds good👍

**Comment by mszabeh** [comment]
@CodeWithDennis 
Hi,
when this PR will be completed?

**Comment by CodeWithDennis** [comment]
> @CodeWithDennis 
> 
> Hi,
> 
> when this PR will be completed?

This is not my PR, he is waiting on a 3rd party.

**Comment by CodeWithDennis** [comment]
@ariaieboy After you finish the PR, can you add a screenshot so I can see how it looks?

**Comment by mszabeh** [comment]
@ariaieboy https://github.com/dipson88/treeselectjs/pull/84 PR. released.

**Comment by CodeWithDennis** [comment]
Is there anything else besides upgrading that needs to be done?

**Comment by ariaieboy** [comment]
> Is there anything else besides upgrading that needs to be done?

Yes we need to pass rtl option to the script.
I will update this PR.

**Pull request closed without merging**
